### ISSUE TITLE
News widget throws an error on page

### ISSUE THREAD

**Issue by Masahigo** [Sitefinity/feather-widgets#1250]
Hi,

We encountered an error after dragging the News widget on the page. We haven't modified it's settings since this happens right after it's added to a page.

Front-end
![news widget server error frontend](https://cloud.githubusercontent.com/assets/9364649/8056016/f715844a-0eac-11e5-9850-95f4d3d4b091.jpg)

Back-end
![news widget server error backend](https://cloud.githubusercontent.com/assets/9364649/8056018/fadda044-0eac-11e5-8dac-c9afd0beff30.jpg)

Here's the error message from the log file:
--
Type : System.MissingMethodException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
Message : Method not found: 'System.String Telerik.Sitefinity.Modules.ContentHelper.AdaptMultilingualFilterExpressionRaw(System.String, System.Globalization.CultureInfo)'.
Source : Telerik.Sitefinity.Frontend
Help link : 
Data : System.Collections.ListDictionaryInternal
TargetSite : System.String AdaptMultilingualFilterExpression(System.String)
HResult : -2146233069
Stack Trace :    at Telerik.Sitefinity.Frontend.Mvc.Models.ContentModelBase.AdaptMultilingualFilterExpression(String filterExpression)
   at Telerik.Sitefinity.Frontend.Mvc.Models.ContentModelBase.UpdateExpression(IQueryable`1 query, Nullable`1 skip, Nullable`1 take, Nullable`1& totalCount)
   at Telerik.Sitefinity.Frontend.Mvc.Models.ContentModelBase.ApplyListSettings(Int32 page, IQueryable`1 query, Nullable`1& totalPages)
   at Telerik.Sitefinity.Frontend.Mvc.Models.ContentModelBase.PopulateListViewModel(Int32 page, IQueryable`1 query, ContentListViewModel viewModel)
   at Telerik.Sitefinity.Frontend.Mvc.Models.ContentModelBase.CreateListViewModel(ITaxon taxonFilter, Int32 page)
   at Telerik.Sitefinity.Frontend.News.Mvc.Controllers.NewsController.Index(Nullable`1 page)
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass13.<InvokeActionMethodWithFilters>b__10()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodWithFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName)
   at Telerik.Sitefinity.Mvc.ControllerWrapper.Execute()
   at Telerik.Sitefinity.Mvc.ControllerActionInvoker.ExecuteController(MvcProxyBase proxyControl)
   at Telerik.Sitefinity.Frontend.Mvc.Infrastructure.Routing.DynamicUrlParamActionInvoker.ExecuteController(MvcProxyBase proxyControl)
--

We're using latest version of Sitefinity (8.0.5716.0) and Feather (1.2.240.0) from the Sitefinity NuGet Server. The website has 4 languages enabled (english, finnish, swedish, polish). The website is run with target .net framework 4.5.

**Comment by manev** [comment]
Hi,

Please accept our appologies. It seems that an API breaking change was introduced in this particular internal build of Sitefinity. A fix will be provided shortly.

**Comment by Masahigo** [comment]
Thanks for the update!

**Comment by Masahigo** [comment]
This seems to be fixed now
http://www.telerik.com/account/VersionNotes.aspx?nb=1&id=4847

I figure it was this one
http://feedback.telerik.com/Project/153/Feedback/Details/157237-itemlanguagefallback-does-not-work

Thank you!
