### ISSUE TITLE
Getting exception when redirecting from controller

### ISSUE THREAD

**Issue by elivnjak** [Sitefinity/feather-widgets#1357]
I'm trying to redirect the page from the widget controller.

Returning  a Redirect("") result from an ActionResult causes a ThreadAborted exception to be logged.

``
Stack Trace :    at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort(Object stateInfo)
   at System.Web.HttpResponse.AbortCurrentThread()
   at Telerik.Sitefinity.Frontend.Mvc.Infrastructure.Routing.DynamicUrlParamActionInvoker.ExecuteController(MvcProxyBase proxyControl)
``

I logged a ticket with Telerik and the support person said it only happens when you enable feather. Just wondering if anyone is experiencing this issue. Or maybe there's a special way to redirect when using feather?

Cheers,
Edin

**Comment by elivnjak** [comment]
Anyone else experiencing this?
