### ISSUE TITLE
ImageGallery: Image details throws exception if Image Gallery displays only one image

### ISSUE THREAD

**Issue by PepiIvanova** [Sitefinity/feather-widgets#546]
Prerequisite: Upload only one image

1. D&D Image Gallery widget
2. Publish page
3. View page
4. Click image to view details

Result: Exception occured while executing the controller. Check error logs for details.

Error log:
Message : Object reference not set to an instance of an object.
Source : Telerik.Sitefinity.Frontend
Help link : 
Data : System.Collections.ListDictionaryInternal
TargetSite : System.String GetDetailPageUrl(Telerik.Sitefinity.Frontend.Mvc.Models.ItemViewModel, System.Guid, Boolean, Int32)
HResult : -2147467261
Stack Trace :    at Telerik.Sitefinity.Frontend.Mvc.Helpers.HyperLinkHelpers.GetDetailPageUrl(ItemViewModel item, Guid detailsPageId, Boolean openInSamePage, Int32 itemIndex)
   at ASP._Page_Frontend_Assembly_Telerik_Sitefinity_Frontend_Media_Mvc_Views_ImageGallery_Detail_DetailPage_cshtml.Execute() in c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\19907183\689f4457\App_Web_detail.detailpage.cshtml.e5948bc5.mknhtly8.0.cs:line 0

**Comment by PepiIvanova** [comment]
Most probably, Model.PreviousItem or Model.NextItem or both in Detail.DetailPage are null.
